name: release
on:
  push:
    branches:
    - '*.x'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          dev: no
          args: --profile --ignore-platform-reqs --prefer-dist
      - uses: cli/gh-extension-precompile@v1
        with:
          build_script_override: "script/build.sh"
